### ISSUE TITLE
Missing /dev/spidev#.# devices

### ISSUE THREAD

**Issue by Nazdravi** [daniel-santos/mcp2210-linux#15]
After unbinding the HID driver and loading the *spidev* and *mcp2210* modules no *spidev#.#* devices occur. This might be correct but what action does produce them? The *usb2spi_bridge1*-device has been created by the driver. Until now I did not change the default SPI slaves configuration. *user/mcp2210-util set config 63* (as root) fails with:
```
open failed: No such file or directory
main: Operation not permitted
```
Thanks for any help
Nazdravi

**Comment by Vishnu-Mohan** [comment]
please find the mask value information from Readme . it might be because configuration flag is set

**Comment by Nazdravi** [comment]
Udev created /dev/usb2spi_bridge1 while mcp2210-util wanted /dev/usb2spi_bridge0. Now /dev/spidev#.#-nodes become created.
Nazdravi
