### ISSUE TITLE
Build failure, struct mismash.

### ISSUE THREAD

**Issue by milkylainen** [daniel-santos/mcp2210-linux#41]
Pulled the git at 09e7ba54e7b8ebe0b1e58f0e7dd30a44c96cc21e.

CC [M]  drivers/spi/mcp2210/mcp2210-gpio.o
drivers/spi/mcp2210/mcp2210-gpio.c: In function 'mcp2210_get':
drivers/spi/mcp2210/mcp2210-gpio.c:385: error: 'struct mcp2210_device' has no member named 'last_poll_gpio'
drivers/spi/mcp2210/mcp2210-gpio.c:396: error: 'struct mcp2210_device' has no member named 'interrupt_event_counter'
drivers/spi/mcp2210/mcp2210-gpio.c:397: error: 'struct mcp2210_device' has no member named 'interrupt_event_counter'

Private device struct mixes gpio and irq configuration and can't build gpio.c without IRQ support. Needs a few rows of cleanup.

**Comment by daniel-santos** [comment]
Hello.  Thanks for your report.  I'll look into this in the next few days.
